import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Intro from "../components/Intro";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-stone-900 text-white font-light`}
      >
        <main className="flex min-h-screen">
          <Intro />
          <div className="pl-[450px] w-full">
            <div className="container mx-auto max-w-[960px]">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
