import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../globals.css";
import { MENUS } from "../const";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <header className="bg-white">
          <div className="container mx-auto max-w-[1280px]">
            <nav className="flex justify-between items-center">
              <div className="text-2xl font-bold">Admin Panel</div>
              <ul className="flex">
                {MENUS.map((menu) => (
                  <li className="p-3" key={menu.id}>
                    <a
                      href={menu.url}
                      className="block rounded p-2 p4 hover:bg-blue-800 hover:text-white"
                    >
                      {menu.label}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
        </header>
        <main className="min-h-screen bg-slate-100 pt-10 pb-10">
          <div className="container mx-auto max-w-[1280px]">{children}</div>
        </main>
      </body>
    </html>
  );
}
